import { chromium } from "playwright";
const D="/private/tmp/claude-501/-Users-raphaelrajan-Desktop-ezeeassist-website/d29d3634-744a-4ccc-b4cd-21ee9d482991/scratchpad";
const [url,name,theme]=process.argv.slice(2);
const b=await chromium.launch();
const p=await b.newPage({viewport:{width:1205,height:900}});
await p.goto(url,{waitUntil:"networkidle"});
if(theme==="dark") await p.evaluate(()=>document.documentElement.classList.add("dark"));
await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=400){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,120));}window.scrollTo(0,0)});
await p.waitForTimeout(1400);
const h=await p.evaluate(()=>document.body.scrollHeight);
await p.setViewportSize({width:1205,height:Math.min(h,9500)});
await p.waitForTimeout(1200);
await p.screenshot({path:`${D}/${name}-${theme}.png`});
await b.close();
